### ISSUE TITLE
linker error "duplicate symbols for architecture x86_64"

### ISSUE THREAD

**Issue by xanpj** [npisanti/ofxAudioFile#10]
Hi,
I am getting a linker error "duplicate symbols for architecture x86_64" when calling audiofile.load()
Any suggestions? Are there any dependencies I am missing or duplicate libraries ofxAudioFile is including that might cause the error.

**Comment by npisanti** [comment]
i'm pretty sure it was my fault, i missed the define guards, i just made a commit to fix it.

`git pull` and try again now, let me know if it's fixed

**Comment by xanpj** [comment]
Hm. I tried with the new verison but no change. I can build the example project, but I cannot call audioFile.load() in my own project, though, the rest works.

**Comment by npisanti** [comment]
please state your opeartive system, oF version, IDE and copy the full error output

**Comment by xanpj** [comment]
Hey, I fixed it. The issue was a duplicate inclusion of _stb_vorbis_ because the addon _ofxMaxim_ that I am using also has a dependency to _stb_vorbis_

However I can set a flag `#define STB_VORBIS_HEADER_ONLY true;` in the stb_vorbis.c file or in the config.make to avoid the duplicate exclusions.

**Comment by npisanti** [comment]
perfect!
