### ISSUE TITLE
loading 16bit file gives me a 32bit file

### ISSUE THREAD

**Issue by anaelisa24** [npisanti/ofxAudioFile#2]
Hi,
So I'm trying to load a 16-bit, 44.1 kHz, mono file, but when I run it, I get twice as many samples as it should while still being a mono file. So when playing the audio I end up with just noise.
Appreciate your help

**Comment by npisanti** [comment]
thanks for reporting!
on which platform are you using ofxAudioFile? the extension is .wav ?

**Comment by anaelisa24** [comment]
I'm running on MacOs and it is a .wav file. However I tried using an mp3 file and get the same issue.

**Comment by npisanti** [comment]
are you loading those files in the `setup()` or while the program is running? i'm doing some test and some samples that loads fine in the setup misbehave when loaded with a file window call

**Comment by anaelisa24** [comment]
I’m loading in the setup() and just printing the number of samples in the
setup gives me twice the real amount of samples.

This is my code and I'm attaching a copy of the audio file

void ofApp::setup(){

    mAudioInput.load("/Users/.../hello2.wav");



    mAudioNumChannels = mAudioInput.channels();

    mAudioNumSamples = mAudioInput.length();

    mAudioSampleRate = mAudioInput.samplerate();



    ofLogNotice()<<mAudioSampleRate<< endl;

    ofLogNotice()<<mAudioNumSamples<<endl;

    ofLogNotice()<<mAudioNumChannels<<endl;


Sent from my iPhone

On Apr 27, 2018, at 3:29 AM, Nicola Pisanti <notifications@github.com>
wrote:

are you loading those files in the setup() or while the program is running?
i'm doing some test and some samples that loads fine in the setup misbehave
when loaded with a file window call

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/npisanti/ofxAudioFile/issues/2#issuecomment-384889211>,
or mute the thread

**Comment by anaelisa24** [comment]
[hello2.wav.zip](https://github.com/npisanti/ofxAudioFile/files/1955034/hello2.wav.zip)

**Comment by anaelisa24** [comment]
I am able to reproduce the sound using your example code. However, I don't understand why I'm getting twice the amount of samples as I get when I use Python or Matlab to read the audio. Can I do fft of these samples and assume it's correct even if the samples look totally different from other languages?

**Comment by npisanti** [comment]
on linux i'm also using `soxi -s hello2.wav' to check the sample buffer length, and it reports the same buffer size (73824). Maybe your tools in python or matlab are allocating twice the buffer size for some reasons, could you check with other tools the buffer length?
