### ISSUE TITLE
Problems with wav files.

### ISSUE THREAD

**Issue by fred-dev** [npisanti/ofxAudioFile#4]
I cannot load .wav files I make with protools (I am guessing they are bwf but with a .wav extensions. I have to convert them with various tools, often without luck. The Mp3 files I export from protools seem to have a 50 50 chance of just playing out noise. 
As an example I get this from a wav file

[pdsp] sample rate: 691284 | length: 3268391 | channels: 2

For an mp3 file with a 44.1 sample rate.

**Comment by npisanti** [comment]
can you please upload some files somewhere so i can try debugging with them?

**Comment by fred-dev** [comment]
Here you go.
https://www.dropbox.com/sh/40vlarnyvid4kzf/AAC8B-5_B2IosMOy15W2EuOYa?dl=0
And I forgot to mention this is on raspberry pi that I have this trouble, although I do find compatibility tricky with this addon across platforms. I did not have enough time to find the patter yet.

**Comment by npisanti** [comment]
so the problems are just on rPi, and it works fine on desktop?

**Comment by npisanti** [comment]
i've updated the included libraries, there should be an improved wav support now, i didn't had the time to test it on rpi but this could fix this issue, so let me know if everything works now =)

**Comment by npisanti** [comment]
mp3 file loading should be still a bit funky, but there's a separate issue thread for that:
https://github.com/npisanti/ofxAudioFile/issues/1

anyway at the moment for more compressed files i prefer .ogg as it isn't a proprietary format
