### ISSUE TITLE
mp3 file loading hang on macOS and Windows

### ISSUE THREAD

**Issue by d3cod3** [npisanti/ofxAudioFile#7]
Hi,
i've found an issue related with dr_mp3 lib, right now you have in your repo the v0.4.2, mp3 file loading is working perfectly on linux but it hangs on OSX and windows.

I've solved it updating dr_mp3 to the last one, v0.4.4 - 2019-05-06

easy fix!

**Comment by npisanti** [comment]
oook, i will update the libs and commit to fix this

**Comment by npisanti** [comment]
closing!
